week1 submit | week0 Folder Name Changed
ID-CC/Team-C pull request #5
Opened 2022-07-04 04:12 UTC by ramer-dev

1주차 완성본
0주차 폴더 이름 통일

2022-07-04 07:38 UTC, magmacoffee commented on SINIZ/week1/recommendID.py
> +        return id
이 함수에서도 len 체크 필요합니다. 프로그래머스의 테케에는 없는듯 한데 input으로 "^^^", "" 넣을 경우 "aaa" 출력되어야하나 에러 발생합니다.

2022-07-04 07:53 UTC, magmacoffee requested changes
recommentID dropDotsInTips 함수 수정해주세요~
-> 이 함수에서도 len 체크 필요합니다. 프로그래머스의 테케에는 없는듯 한데 input으로 "^^^", "" 넣을 경우 "aaa" 출력되어야하나 에러 발생합니다.

2022-07-04 07:55 UTC, magmacoffee approved these changes

2022-07-04 13:52 UTC, zooxop commented on SINIZ/week1/recommendID.py
> +        return id
위 코드에서 `len()` 함수는 사용하지 않아도 될 것 같습니다!

```python
text = 'asdf'

print(text[1:])  # sdf
print(text[:-1])  # asd
print(text[1:-1])  # sd
```

2022-07-04 17:33 UTC, ramer-dev commented on SINIZ/week1/recommendID.py
> +        return id
으따 했당게요

2022-07-04 17:34 UTC, ramer-dev commented on SINIZ/week1/recommendID.py
> +        return id
아이구 했엄시라

2022-07-07 09:09 UTC, magmacoffee commented on SINIZ/week1/ranking_success.py
> +    for q in queries:
똑같은 쿼리가 들어올 수 있어서 결과를 메모이제이션 해두면 시간적으로 효율이 더 좋아질 듯 합니다!

2022-07-07 09:09 UTC, magmacoffee approved these changes
고생하셨습니다~ 아래 코멘트는 참고용으로 확인 부탁드려요!

2022-07-08 08:58 UTC, zooxop approved these changes
잘 봤습니다! 고생하셨습니다!

2022-07-08 08:58 UTC, zooxop commented on SINIZ/week1/ranking_success.py
> +                    info_dict[lang + job + career + food] = []
경우의 수를 모두 딕셔너리로 정의해놓는 아이디어 잘 봤습니다!

2022-07-08 08:58 UTC, zooxop commented on SINIZ/week1/ranking_success.py
> +        info_dict[key].sort()
@magmacoffee 

> 모든 경우를 Sorting 하는 것 보단 해당 key를 가진 리스트에서 질의할때 Sorting 하는 것도 좋을 것 같아요!

저도 달아주신 의견에 동의해서, 해당 key를 가진 리스트를 탐색하기 직전에 정렬하도록 구현해봤는데요,
프로그래머스의 효율성 테스트 케이스는 똑같은 쿼리를 무수히 많이 호출하는 식으로 테스트를 돌리는 것 같아요.
오히려 sort 횟수가 많아져서, 효율성 테스트 통과를 못하더라구요.

자세하게 확인해봐야겠지만, 경험 공유해봅니다..!

2022-07-10 06:48 UTC, merged